// Thin re-export wrapper — preserves the original public API
export {
  isPushSupported,
  getPermissionState,
  getPushSupport,
  requestPermission,
  subscribeToPush,
  unsubscribeFromPush,
  getNotificationPreferences,
  updateNotificationPreferences,
  getDefaultPreferences,
  createNewBookingNotification,
  createReminderNotification,
  createCancellationNotification,
  createRescheduleNotification,
  createDailySummaryNotification,
  urlBase64ToUint8Array,
  isQuietHours,
  getNotificationTypeLabel,
} from "./push-notification/index";
