#!/usr/bin/env python3
"""Generate products.ts and personalliste.ts for dashboard locales from embedded translations."""
from __future__ import annotations

import os

ROOT = os.path.join(os.path.dirname(__file__), "..", "src", "i18n", "locales")

PRODUCTS: dict[str, dict[str, str]] = {
    "ar": {
        "title": "المنتجات",
        "description": "إدارة المخزون والمنتجات",
        "noProducts": "لا توجد منتجات بعد",
        "createFirst": "أنشئ منتجك الأول",
        "name": "الاسم",
        "price": "السعر",
        "stock": "المخزون",
        "sku": "رمز المنتج",
        "status": "الحالة",
        "actions": "إجراءات",
        "create": "إنشاء منتج",
        "edit": "تعديل",
        "delete": "حذف",
        "save": "حفظ",
        "cancel": "إلغاء",
        "active": "نشط",
        "inactive": "غير نشط",
        "namePlaceholder": "اسم المنتج",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "so": {
        "title": "Alaabada",
        "description": "Maamul kaydka iyo alaabada",
        "noProducts": "Weli alaabo ma jirto",
        "createFirst": "Abuur alaabadaada ugu horeysa",
        "name": "Magac",
        "price": "Qiimo",
        "stock": "Kayd",
        "sku": "SKU",
        "status": "Xaalad",
        "actions": "Ficillo",
        "create": "Abuur alaab",
        "edit": "Wax ka beddel",
        "delete": "Tirtir",
        "save": "Kaydi",
        "cancel": "Jooji",
        "active": "Firfircoon",
        "inactive": "Aan firfircoonayn",
        "namePlaceholder": "Magaca alaabta",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "ti": {
        "title": "ፈርኦታት",
        "description": "ናይ ምሕዳስን ፈርኦታትን ምምሕዳስ",
        "noProducts": "ክሳዕ ሕጂ ፈርኦታት የለን",
        "createFirst": "ናይ ቀዳም ፈርኦትካ ፍጠር",
        "name": "ስም",
        "price": "ዋጋ",
        "stock": "ክምችት",
        "sku": "SKU",
        "status": "ኩነታት",
        "actions": "ተግባራት",
        "create": "ፈርኦት ፍጠር",
        "edit": "ኣመሓይሽ",
        "delete": "ሰርዝ",
        "save": "ዓቅብ",
        "cancel": "ኣትርፍ",
        "active": "ንቁህ",
        "inactive": "ንቁህ ኣይኮነን",
        "namePlaceholder": "ስም ፈርኦት",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "am": {
        "title": "ምርቶች",
        "description": "ክምችት እና ምርቶችን ያቀናብሩ",
        "noProducts": "እስካሁን ምርቶች የሉም",
        "createFirst": "የመጀመሪያውን ምርትዎን ይፍጠሩ",
        "name": "ስም",
        "price": "ዋጋ",
        "stock": "ክምችት",
        "sku": "SKU",
        "status": "ሁኔታ",
        "actions": "ድርጊቶች",
        "create": "ምርት ፍጠር",
        "edit": "አርትዖት",
        "delete": "ሰርዝ",
        "save": "አስቀምጥ",
        "cancel": "ተወው",
        "active": "ንቁ",
        "inactive": "ንቁ አይደለም",
        "namePlaceholder": "የምርት ስም",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "tr": {
        "title": "Ürünler",
        "description": "Envanter ve ürünleri yönetin",
        "noProducts": "Henüz ürün yok",
        "createFirst": "İlk ürününüzü oluşturun",
        "name": "Ad",
        "price": "Fiyat",
        "stock": "Stok",
        "sku": "SKU",
        "status": "Durum",
        "actions": "İşlemler",
        "create": "Ürün oluştur",
        "edit": "Düzenle",
        "delete": "Sil",
        "save": "Kaydet",
        "cancel": "İptal",
        "active": "Aktif",
        "inactive": "Pasif",
        "namePlaceholder": "Ürün adı",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "pl": {
        "title": "Produkty",
        "description": "Zarządzaj magazynem i produktami",
        "noProducts": "Brak produktów",
        "createFirst": "Utwórz pierwszy produkt",
        "name": "Nazwa",
        "price": "Cena",
        "stock": "Stan",
        "sku": "SKU",
        "status": "Status",
        "actions": "Akcje",
        "create": "Utwórz produkt",
        "edit": "Edytuj",
        "delete": "Usuń",
        "save": "Zapisz",
        "cancel": "Anuluj",
        "active": "Aktywny",
        "inactive": "Nieaktywny",
        "namePlaceholder": "Nazwa produktu",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "vi": {
        "title": "Sản phẩm",
        "description": "Quản lý kho và sản phẩm",
        "noProducts": "Chưa có sản phẩm",
        "createFirst": "Tạo sản phẩm đầu tiên",
        "name": "Tên",
        "price": "Giá",
        "stock": "Tồn kho",
        "sku": "SKU",
        "status": "Trạng thái",
        "actions": "Thao tác",
        "create": "Tạo sản phẩm",
        "edit": "Sửa",
        "delete": "Xóa",
        "save": "Lưu",
        "cancel": "Hủy",
        "active": "Đang hoạt động",
        "inactive": "Không hoạt động",
        "namePlaceholder": "Tên sản phẩm",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "zh": {
        "title": "产品",
        "description": "管理库存与产品",
        "noProducts": "暂无产品",
        "createFirst": "创建您的第一个产品",
        "name": "名称",
        "price": "价格",
        "stock": "库存",
        "sku": "SKU",
        "status": "状态",
        "actions": "操作",
        "create": "创建产品",
        "edit": "编辑",
        "delete": "删除",
        "save": "保存",
        "cancel": "取消",
        "active": "启用",
        "inactive": "停用",
        "namePlaceholder": "产品名称",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "tl": {
        "title": "Mga Produkto",
        "description": "Pamahalaan ang imbentaryo at produkto",
        "noProducts": "Wala pang produkto",
        "createFirst": "Gumawa ng unang produkto",
        "name": "Pangalan",
        "price": "Presyo",
        "stock": "Stok",
        "sku": "SKU",
        "status": "Status",
        "actions": "Mga aksyon",
        "create": "Gumawa ng produkto",
        "edit": "I-edit",
        "delete": "Tanggalin",
        "save": "I-save",
        "cancel": "Kanselahin",
        "active": "Aktibo",
        "inactive": "Hindi aktibo",
        "namePlaceholder": "Pangalan ng produkto",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "fa": {
        "title": "محصولات",
        "description": "مدیریت موجودی و محصولات",
        "noProducts": "هنوز محصولی نیست",
        "createFirst": "اولین محصول خود را بسازید",
        "name": "نام",
        "price": "قیمت",
        "stock": "موجودی",
        "sku": "SKU",
        "status": "وضعیت",
        "actions": "اقدامات",
        "create": "ایجاد محصول",
        "edit": "ویرایش",
        "delete": "حذف",
        "save": "ذخیره",
        "cancel": "لغو",
        "active": "فعال",
        "inactive": "غیرفعال",
        "namePlaceholder": "نام محصول",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "dar": {
        "title": "محصولات",
        "description": "مدیریت موجودی و محصولات",
        "noProducts": "هنوز محصولی وجود ندارد",
        "createFirst": "اولین محصول خود را بسازید",
        "name": "نام",
        "price": "قیمت",
        "stock": "موجودی",
        "sku": "SKU",
        "status": "وضعیت",
        "actions": "اقدامات",
        "create": "ایجاد محصول",
        "edit": "ویرایش",
        "delete": "حذف",
        "save": "ذخیره",
        "cancel": "لغو",
        "active": "فعال",
        "inactive": "غیرفعال",
        "namePlaceholder": "نام محصول",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "ur": {
        "title": "مصنوعات",
        "description": "انوینٹری اور مصنوعات منظم کریں",
        "noProducts": "ابھی کوئی مصنوعہ نہیں",
        "createFirst": "اپنی پہلی مصنوعہ بنائیں",
        "name": "نام",
        "price": "قیمت",
        "stock": "اسٹاک",
        "sku": "SKU",
        "status": "حالت",
        "actions": "اعمال",
        "create": "مصنوعہ بنائیں",
        "edit": "ترمیم",
        "delete": "حذف",
        "save": "محفوظ",
        "cancel": "منسوخ",
        "active": "فعال",
        "inactive": "غیر فعال",
        "namePlaceholder": "مصنوعہ کا نام",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
    "hi": {
        "title": "उत्पाद",
        "description": "अपनी इन्वेंटरी और उत्पाद प्रबंधित करें",
        "noProducts": "अभी कोई उत्पाद नहीं",
        "createFirst": "अपना पहला उत्पाद बनाएँ",
        "name": "नाम",
        "price": "मूल्य",
        "stock": "स्टॉक",
        "sku": "SKU",
        "status": "स्थिति",
        "actions": "कार्रवाई",
        "create": "उत्पाद बनाएँ",
        "edit": "संपादित करें",
        "delete": "हटाएँ",
        "save": "सहेजें",
        "cancel": "रद्द करें",
        "active": "सक्रिय",
        "inactive": "निष्क्रिय",
        "namePlaceholder": "उत्पाद नाम",
        "pricePlaceholder": "0.00",
        "stockPlaceholder": "0",
        "skuPlaceholder": "SKU-001",
    },
}

PERSONALLISTE: dict[str, dict[str, str]] = {
    "ar": {
        "title": "سجل الموظفين",
        "description": "سجل قانوني لمن كان في العمل. تسجيل الدخول والخروج.",
        "noSalon": "لا يوجد صالون مرتبط بحسابك. أكمل الإعداد أولاً.",
        "loadError": "تعذر تحميل سجل الموظفين.",
        "dateFrom": "من تاريخ",
        "dateTo": "إلى تاريخ",
        "exportCsv": "تصدير CSV",
        "exportPdf": "تصدير PDF",
        "colDate": "التاريخ",
        "colEmployee": "الموظف",
        "colCheckIn": "تسجيل دخول",
        "colCheckOut": "تسجيل خروج",
        "colDuration": "المدة",
        "colStatus": "الحالة",
        "colChangedBy": "عُدّل بواسطة / متى",
        "statusOk": "موافق",
        "statusEdited": "معدّل",
        "emptyTitle": "لا توجد إدخالات في الفترة",
        "emptyDescription": "اختر فترة وسجّل الإدخالات اختياريًا.",
        "registerEntry": "تسجيل إدخال",
        "edit": "تعديل",
        "registerDialogTitle": "تسجيل إدخال",
        "registerDialogDescription": "أضف وقت الدخول والخروج لموظف.",
        "editDialogTitle": "تعديل الإدخال",
        "editDialogDescription": "تُسجَّل التغييرات بحالة «معدّل».",
        "employeePlaceholder": "اختر موظفًا…",
        "cancel": "إلغاء",
        "save": "حفظ",
        "saving": "جارٍ الحفظ…",
        "editNotSignedIn": "غير مسجّل الدخول",
    },
    "so": {
        "title": "Diiwaanka shaqaalaha",
        "description": "Diiwaan sharci ah oo ku saabsan cidda ka shaqaysay. Galitaan iyo bixitaan.",
        "noSalon": "Salon lama xidhiidhin isticmaalahaaga. Fadlan dhammaystir bilowga hore.",
        "loadError": "Lama soo geli karo diiwaanka shaqaalaha.",
        "dateFrom": "Laga bilaabo taariikhda",
        "dateTo": "Ilaa taariikhda",
        "exportCsv": "Dhoof CSV",
        "exportPdf": "Dhoof PDF",
        "colDate": "Taariikh",
        "colEmployee": "Shaqaale",
        "colCheckIn": "Galitaan",
        "colCheckOut": "Bixitaan",
        "colDuration": "Muddada",
        "colStatus": "Xaalad",
        "colChangedBy": "Wax ka beddelay / goorta",
        "statusOk": "Hagaag",
        "statusEdited": "Wax la beddelay",
        "emptyTitle": "Wax gelin ah muddada ma jiro",
        "emptyDescription": "Dooro muddada oo si ikhtiyaari ah u diiwaangeli gelitaan.",
        "registerEntry": "Diiwaangeli gelin",
        "edit": "Wax ka beddel",
        "registerDialogTitle": "Diiwaangeli gelin",
        "registerDialogDescription": "Ku dar galitaan iyo bixitaan shaqaale.",
        "editDialogTitle": "Wax ka beddel gelin",
        "editDialogDescription": "Isbeddelada waxaa lagu diiwaangeliyaa xaaladda «wax la beddelay».",
        "employeePlaceholder": "Dooro shaqaale…",
        "cancel": "Jooji",
        "save": "Kaydi",
        "saving": "Waa la kaydiyaa…",
        "editNotSignedIn": "Lama soo galin",
    },
    "ti": {
        "title": "መዝገብ ሰራሕተኛታት",
        "description": "ናይ ሕጊ መዝገብ መን እዩ ኣብ ስራሕ ከምዘሎ። ምእታውን ምውጻእን።",
        "noSalon": "ምስ ተጠቃሚኻ ሳሎን ኣይተራኸበን። ቅድሚ ሕጂ ምጅማር ውደእ።",
        "loadError": "መዝገብ ሰራሕተኛታት ክጫን ኣይከኣለን።",
        "dateFrom": "ካብ ዕለት",
        "dateTo": "ክሳዕ ዕለት",
        "exportCsv": "CSV ምውጻእ",
        "exportPdf": "PDF ምውጻእ",
        "colDate": "ዕለት",
        "colEmployee": "ሰራሕተኛ",
        "colCheckIn": "ምእታው",
        "colCheckOut": "ምውጻእ",
        "colDuration": "እዋን",
        "colStatus": "ኩነታት",
        "colChangedBy": "ዝቐየረ / መእለዊ",
        "statusOk": "ሕራይ",
        "statusEdited": "ተሰሪሑ",
        "emptyTitle": "ኣብ እዋን ኣይኮነን መዝገብ",
        "emptyDescription": "እዋን ምረጽ እና ብምሕጽረት መዝገብ።",
        "registerEntry": "መዝገብ ምዝገባ",
        "edit": "ምምሕዳስ",
        "registerDialogTitle": "መዝገብ ምዝገባ",
        "registerDialogDescription": "ናይ ሰራሕተኛ ምእታውን ምውጻእን ወስኽ።",
        "editDialogTitle": "ምምሕዳስ መዝገብ",
        "editDialogDescription": "ለውጥታት ብኩነታት «ተሰሪሑ» ይዝገቡ።",
        "employeePlaceholder": "ሰራሕተኛ ምረጽ…",
        "cancel": "ኣትርፍ",
        "save": "ዓቅብ",
        "saving": "ኣብ ምዕቃብ…",
        "editNotSignedIn": "ኣይተእተወን",
    },
    "am": {
        "title": "የሰራተኞች መዝገብ",
        "description": "በስራ ላይ ያሉ ሰዎች ህጋዊ መዝገብ። መግባት እና መውጣት።",
        "noSalon": "ከተማሚያዎ ጋር ሳሎን አልተገናኘም። እባክዎ መጀመሪያውን ያጠናቅቁ።",
        "loadError": "የሰራተኞች መዝገብ መጫን አልተቻለም።",
        "dateFrom": "ከቀን",
        "dateTo": "እስከ ቀን",
        "exportCsv": "CSV ላክ",
        "exportPdf": "PDF ላክ",
        "colDate": "ቀን",
        "colEmployee": "ሰራተኛ",
        "colCheckIn": "መግቢያ",
        "colCheckOut": "መውጫ",
        "colDuration": "የጊዜ ርዝመት",
        "colStatus": "ሁኔታ",
        "colChangedBy": "የቀየረ / መቼ",
        "statusOk": "እሺ",
        "statusEdited": "ተስተካክሏል",
        "emptyTitle": "በጊዜው ውስጥ ግቤቶች የሉም",
        "emptyDescription": "ጊዜ ይምረጡ እና በአማራጭ ግቤቶችን ይመዝግቡ።",
        "registerEntry": "ግብዣ መዝግብ",
        "edit": "አርትዖት",
        "registerDialogTitle": "ግብዣ መዝግብ",
        "registerDialogDescription": "ለሰራተኛ መግቢያ እና መውጫ ጊዜ ያክሉ።",
        "editDialogTitle": "ግብዣ አርትዖት",
        "editDialogDescription": "ለውጦች በ«ተስተካክሏል» ሁኔታ ይመዘገባሉ።",
        "employeePlaceholder": "ሰራተኛ ይምረጡ…",
        "cancel": "ተወው",
        "save": "አስቀምጥ",
        "saving": "በመቀመጥ ላይ…",
        "editNotSignedIn": "አልገቡም",
    },
    "tr": {
        "title": "Personel listesi",
        "description": "Kimlerin işte olduğuna dair yasal kayıt. Giriş ve çıkış.",
        "noSalon": "Hesabınıza bağlı salon yok. Önce kurulumu tamamlayın.",
        "loadError": "Personel listesi yüklenemedi.",
        "dateFrom": "Başlangıç tarihi",
        "dateTo": "Bitiş tarihi",
        "exportCsv": "CSV dışa aktar",
        "exportPdf": "PDF dışa aktar",
        "colDate": "Tarih",
        "colEmployee": "Çalışan",
        "colCheckIn": "Giriş",
        "colCheckOut": "Çıkış",
        "colDuration": "Süre",
        "colStatus": "Durum",
        "colChangedBy": "Değiştiren / ne zaman",
        "statusOk": "Tamam",
        "statusEdited": "Düzenlendi",
        "emptyTitle": "Dönemde kayıt yok",
        "emptyDescription": "Dönemi seçin ve isteğe bağlı kayıt ekleyin.",
        "registerEntry": "Kayıt ekle",
        "edit": "Düzenle",
        "registerDialogTitle": "Kayıt ekle",
        "registerDialogDescription": "Bir çalışan için giriş ve çıkış saatlerini ekleyin.",
        "editDialogTitle": "Kaydı düzenle",
        "editDialogDescription": "Değişiklikler «düzenlendi» durumuyla kaydedilir.",
        "employeePlaceholder": "Çalışan seçin…",
        "cancel": "İptal",
        "save": "Kaydet",
        "saving": "Kaydediliyor…",
        "editNotSignedIn": "Oturum açılmamış",
    },
    "pl": {
        "title": "Lista obecności",
        "description": "Prawny zapis kto był w pracy. Wejście i wyjście.",
        "noSalon": "Brak powiązanego salonu z kontem. Ukończ najpierw konfigurację.",
        "loadError": "Nie udało się wczytać listy obecności.",
        "dateFrom": "Data od",
        "dateTo": "Data do",
        "exportCsv": "Eksport CSV",
        "exportPdf": "Eksport PDF",
        "colDate": "Data",
        "colEmployee": "Pracownik",
        "colCheckIn": "Wejście",
        "colCheckOut": "Wyjście",
        "colDuration": "Czas trwania",
        "colStatus": "Status",
        "colChangedBy": "Zmienione przez / kiedy",
        "statusOk": "Ok",
        "statusEdited": "Edytowano",
        "emptyTitle": "Brak wpisów w okresie",
        "emptyDescription": "Wybierz okres i opcjonalnie zarejestruj wpisy.",
        "registerEntry": "Zarejestruj wpis",
        "edit": "Edytuj",
        "registerDialogTitle": "Zarejestruj wpis",
        "registerDialogDescription": "Dodaj czas wejścia i wyjścia pracownika.",
        "editDialogTitle": "Edytuj wpis",
        "editDialogDescription": "Zmiany są zapisywane ze statusem «edytowano».",
        "employeePlaceholder": "Wybierz pracownika…",
        "cancel": "Anuluj",
        "save": "Zapisz",
        "saving": "Zapisywanie…",
        "editNotSignedIn": "Nie zalogowano",
    },
    "vi": {
        "title": "Sổ điểm danh",
        "description": "Hồ sơ pháp lý về người có mặt tại chỗ. Giờ vào và ra.",
        "noSalon": "Chưa liên kết salon với tài khoản. Vui lòng hoàn tất thiết lập trước.",
        "loadError": "Không tải được sổ điểm danh.",
        "dateFrom": "Từ ngày",
        "dateTo": "Đến ngày",
        "exportCsv": "Xuất CSV",
        "exportPdf": "Xuất PDF",
        "colDate": "Ngày",
        "colEmployee": "Nhân viên",
        "colCheckIn": "Vào ca",
        "colCheckOut": "Ra ca",
        "colDuration": "Thời lượng",
        "colStatus": "Trạng thái",
        "colChangedBy": "Sửa bởi / lúc nào",
        "statusOk": "Ok",
        "statusEdited": "Đã chỉnh sửa",
        "emptyTitle": "Không có bản ghi trong kỳ",
        "emptyDescription": "Chọn kỳ và tùy chọn ghi nhận bản ghi.",
        "registerEntry": "Ghi nhận",
        "edit": "Sửa",
        "registerDialogTitle": "Ghi nhận",
        "registerDialogDescription": "Thêm giờ vào và ra cho nhân viên.",
        "editDialogTitle": "Sửa bản ghi",
        "editDialogDescription": "Thay đổi được lưu với trạng thái «đã chỉnh sửa».",
        "employeePlaceholder": "Chọn nhân viên…",
        "cancel": "Hủy",
        "save": "Lưu",
        "saving": "Đang lưu…",
        "editNotSignedIn": "Chưa đăng nhập",
    },
    "zh": {
        "title": "员工签到表",
        "description": "谁在岗的法定记录。签到与签退。",
        "noSalon": "账户未关联沙龙。请先完成入驻设置。",
        "loadError": "无法加载员工签到表。",
        "dateFrom": "开始日期",
        "dateTo": "结束日期",
        "exportCsv": "导出 CSV",
        "exportPdf": "导出 PDF",
        "colDate": "日期",
        "colEmployee": "员工",
        "colCheckIn": "签到",
        "colCheckOut": "签退",
        "colDuration": "时长",
        "colStatus": "状态",
        "colChangedBy": "修改人 / 时间",
        "statusOk": "正常",
        "statusEdited": "已编辑",
        "emptyTitle": "该期间无记录",
        "emptyDescription": "选择期间并可选择登记记录。",
        "registerEntry": "登记记录",
        "edit": "编辑",
        "registerDialogTitle": "登记记录",
        "registerDialogDescription": "为员工添加入与退时间。",
        "editDialogTitle": "编辑记录",
        "editDialogDescription": "更改将以「已编辑」状态保存。",
        "employeePlaceholder": "选择员工…",
        "cancel": "取消",
        "save": "保存",
        "saving": "正在保存…",
        "editNotSignedIn": "未登录",
    },
    "tl": {
        "title": "Rehistro ng staff",
        "description": "Legal na talaan kung sino ang nasa trabaho. Check-in at check-out.",
        "noSalon": "Walang salon na naka-link sa account mo. Kumpletuhin muna ang onboarding.",
        "loadError": "Hindi ma-load ang staff register.",
        "dateFrom": "Mula petsa",
        "dateTo": "Hanggang petsa",
        "exportCsv": "I-export ang CSV",
        "exportPdf": "I-export ang PDF",
        "colDate": "Petsa",
        "colEmployee": "Empleyado",
        "colCheckIn": "Check-in",
        "colCheckOut": "Check-out",
        "colDuration": "Tagal",
        "colStatus": "Status",
        "colChangedBy": "Binago ni / kailan",
        "statusOk": "Ok",
        "statusEdited": "Na-edit",
        "emptyTitle": "Walang entry sa panahon",
        "emptyDescription": "Pumili ng panahon at opsyonal na magrehistro ng entry.",
        "registerEntry": "Magrehistro ng entry",
        "edit": "I-edit",
        "registerDialogTitle": "Magrehistro ng entry",
        "registerDialogDescription": "Magdagdag ng check-in at check-out para sa empleyado.",
        "editDialogTitle": "I-edit ang entry",
        "editDialogDescription": "Ang mga pagbabago ay naitatala na may status na «na-edit».",
        "employeePlaceholder": "Pumili ng empleyado…",
        "cancel": "Kanselahin",
        "save": "I-save",
        "saving": "Sine-save…",
        "editNotSignedIn": "Hindi naka-sign in",
    },
    "fa": {
        "title": "ثبت حضور کارکنان",
        "description": "سابقه قانونی حضور در محل کار. ورود و خروج.",
        "noSalon": "سالنی به حساب شما متصل نیست. ابتدا راه‌اندازی را تکمیل کنید.",
        "loadError": "بارگذاری ثبت حضور ممکن نشد.",
        "dateFrom": "از تاریخ",
        "dateTo": "تا تاریخ",
        "exportCsv": "خروجی CSV",
        "exportPdf": "خروجی PDF",
        "colDate": "تاریخ",
        "colEmployee": "کارمند",
        "colCheckIn": "ورود",
        "colCheckOut": "خروج",
        "colDuration": "مدت",
        "colStatus": "وضعیت",
        "colChangedBy": "تغییر توسط / زمان",
        "statusOk": "تأیید",
        "statusEdited": "ویرایش‌شده",
        "emptyTitle": "در این بازه ورودی نیست",
        "emptyDescription": "بازه را انتخاب کنید و در صورت تمایل ورودی ثبت کنید.",
        "registerEntry": "ثبت ورودی",
        "edit": "ویرایش",
        "registerDialogTitle": "ثبت ورودی",
        "registerDialogDescription": "زمان ورود و خروج کارمند را اضافه کنید.",
        "editDialogTitle": "ویرایش ورودی",
        "editDialogDescription": "تغییرات با وضعیت «ویرایش‌شده» ذخیره می‌شوند.",
        "employeePlaceholder": "کارمند را انتخاب کنید…",
        "cancel": "لغو",
        "save": "ذخیره",
        "saving": "در حال ذخیره…",
        "editNotSignedIn": "وارد نشده‌اید",
    },
    "dar": {
        "title": "ثبت حضور کارکنان",
        "description": "سابقه قانونی حضور در محل کار. ورود و خروج.",
        "noSalon": "سالنی به حساب شما وصل نیست. ابتدا راه‌اندازی را تکمیل کنید.",
        "loadError": "بارگذاری ثبت حضور ممکن نشد.",
        "dateFrom": "از تاریخ",
        "dateTo": "تا تاریخ",
        "exportCsv": "خروجی CSV",
        "exportPdf": "خروجی PDF",
        "colDate": "تاریخ",
        "colEmployee": "کارمند",
        "colCheckIn": "ورود",
        "colCheckOut": "خروج",
        "colDuration": "مدت",
        "colStatus": "وضعیت",
        "colChangedBy": "تغییر توسط / زمان",
        "statusOk": "تأیید",
        "statusEdited": "ویرایش‌شده",
        "emptyTitle": "در این بازه ورودی نیست",
        "emptyDescription": "بازه را انتخاب کنید و در صورت تمایل ورودی ثبت کنید.",
        "registerEntry": "ثبت ورودی",
        "edit": "ویرایش",
        "registerDialogTitle": "ثبت ورودی",
        "registerDialogDescription": "زمان ورود و خروج کارمند را اضافه کنید.",
        "editDialogTitle": "ویرایش ورودی",
        "editDialogDescription": "تغییرات با وضعیت «ویرایش‌شده» ذخیره می‌شوند.",
        "employeePlaceholder": "کارمند را انتخاب کنید…",
        "cancel": "لغو",
        "save": "ذخیره",
        "saving": "در حال ذخیره…",
        "editNotSignedIn": "وارد نشده‌اید",
    },
    "ur": {
        "title": "اسٹاف رجسٹر",
        "description": "کام پر موجود افراد کا قانونی ریکارڈ۔ چیک اِن اور چیک آؤٹ۔",
        "noSalon": "آپ کے اکاؤنٹ سے کوئی سیلون منسلک نہیں۔ پہلے آن بورڈنگ مکمل کریں۔",
        "loadError": "اسٹاف رجسٹر لوڈ نہیں ہو سکا۔",
        "dateFrom": "تاریخ سے",
        "dateTo": "تاریخ تک",
        "exportCsv": "CSV برآمد",
        "exportPdf": "PDF برآمد",
        "colDate": "تاریخ",
        "colEmployee": "ملازم",
        "colCheckIn": "چیک اِن",
        "colCheckOut": "چیک آؤٹ",
        "colDuration": "دورانیہ",
        "colStatus": "حالت",
        "colChangedBy": "تبدیل کردہ / کب",
        "statusOk": "ٹھیک",
        "statusEdited": "ترمیم شدہ",
        "emptyTitle": "مدت میں کوئی اندراج نہیں",
        "emptyDescription": "مدت منتخب کریں اور اختیاری طور پر اندراج کریں۔",
        "registerEntry": "اندراج رجسٹر کریں",
        "edit": "ترمیم",
        "registerDialogTitle": "اندراج رجسٹر کریں",
        "registerDialogDescription": "ملازم کے لیے چیک اِن اور چیک آؤٹ کا وقت شامل کریں۔",
        "editDialogTitle": "اندراج میں ترمیم",
        "editDialogDescription": "تبدیلیاں «ترمیم شدہ» حالت میں محفوظ ہوتی ہیں۔",
        "employeePlaceholder": "ملازم منتخب کریں…",
        "cancel": "منسوخ",
        "save": "محفوظ",
        "saving": "محفوظ ہو رہا ہے…",
        "editNotSignedIn": "سائن اِن نہیں",
    },
    "hi": {
        "title": "स्टाफ रजिस्टर",
        "description": "कौन काम पर था, इसका कानूनी रिकॉर्ड। चेक-इन और चेक-आउट।",
        "noSalon": "आपके खाते से कोई सैलून लिंक नहीं। पहले ऑनबोर्डिंग पूरी करें।",
        "loadError": "स्टाफ रजिस्टर लोड नहीं हो सका।",
        "dateFrom": "तारीख से",
        "dateTo": "तारीख तक",
        "exportCsv": "CSV निर्यात",
        "exportPdf": "PDF निर्यात",
        "colDate": "तारीख",
        "colEmployee": "कर्मचारी",
        "colCheckIn": "चेक-इन",
        "colCheckOut": "चेक-आउट",
        "colDuration": "अवधि",
        "colStatus": "स्थिति",
        "colChangedBy": "संशोधित करने वाला / कब",
        "statusOk": "ठीक",
        "statusEdited": "संपादित",
        "emptyTitle": "अवधि में कोई प्रविष्टि नहीं",
        "emptyDescription": "अवधि चुनें और वैकल्पिक रूप से प्रविष्टियाँ दर्ज करें।",
        "registerEntry": "प्रविष्टि दर्ज करें",
        "edit": "संपादित करें",
        "registerDialogTitle": "प्रविष्टि दर्ज करें",
        "registerDialogDescription": "कर्मचारी के लिए चेक-इन और चेक-आउट समय जोड़ें।",
        "editDialogTitle": "प्रविष्टि संपादित करें",
        "editDialogDescription": "परिवर्तन «संपादित» स्थिति के साथ सहेजे जाते हैं।",
        "employeePlaceholder": "कर्मचारी चुनें…",
        "cancel": "रद्द करें",
        "save": "सहेजें",
        "saving": "सहेजा जा रहा है…",
        "editNotSignedIn": "साइन इन नहीं",
    },
}


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_products(code: str, d: dict[str, str]) -> None:
    path = os.path.join(ROOT, code, "products.ts")
    keys = [
        "title",
        "description",
        "noProducts",
        "createFirst",
        "name",
        "price",
        "stock",
        "sku",
        "status",
        "actions",
        "create",
        "edit",
        "delete",
        "save",
        "cancel",
        "active",
        "inactive",
        "namePlaceholder",
        "pricePlaceholder",
        "stockPlaceholder",
        "skuPlaceholder",
    ]
    lines = [
        "import type { TranslationNamespaces } from '../../types';",
        "",
        "export const products: TranslationNamespaces['products'] = {",
    ]
    for k in keys:
        lines.append(f'    {k}: "{esc(d[k])}",')
    lines.append("  };")
    lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def write_personalliste(code: str, d: dict[str, str]) -> None:
    path = os.path.join(ROOT, code, "personalliste.ts")
    keys = [
        "title",
        "description",
        "noSalon",
        "loadError",
        "dateFrom",
        "dateTo",
        "exportCsv",
        "exportPdf",
        "colDate",
        "colEmployee",
        "colCheckIn",
        "colCheckOut",
        "colDuration",
        "colStatus",
        "colChangedBy",
        "statusOk",
        "statusEdited",
        "emptyTitle",
        "emptyDescription",
        "registerEntry",
        "edit",
        "registerDialogTitle",
        "registerDialogDescription",
        "editDialogTitle",
        "editDialogDescription",
        "employeePlaceholder",
        "cancel",
        "save",
        "saving",
        "editNotSignedIn",
    ]
    lines = [
        "import type { TranslationNamespaces } from '../../types';",
        "",
        "export const personalliste: TranslationNamespaces['personalliste'] = {",
    ]
    for k in keys:
        lines.append(f'    {k}: "{esc(d[k])}",')
    lines.append("  };")
    lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> None:
    for code in PRODUCTS:
        write_products(code, PRODUCTS[code])
        write_personalliste(code, PERSONALLISTE[code])
    print("Wrote products.ts and personalliste.ts for:", ", ".join(sorted(PRODUCTS)))


if __name__ == "__main__":
    main()
